
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.i18n
{
public partial class TbI18L
{
    private readonly System.Collections.Generic.Dictionary<string, i18n.I18L> _dataMap;
    private readonly System.Collections.Generic.List<i18n.I18L> _dataList;
    
    public TbI18L(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, i18n.I18L>();
        _dataList = new System.Collections.Generic.List<i18n.I18L>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            i18n.I18L _v;
            _v = i18n.I18L.DeserializeI18L(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, i18n.I18L> DataMap => _dataMap;
    public System.Collections.Generic.List<i18n.I18L> DataList => _dataList;

    public i18n.I18L GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public i18n.I18L Get(string key) => _dataMap[key];
    public i18n.I18L this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

