
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.i18n
{
public sealed partial class I18L : Luban.BeanBase
{
    public I18L(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        OriginText = _buf.ReadString();
        TextTw = _buf.ReadString();
        TextEn = _buf.ReadString();
    }

    public static I18L DeserializeI18L(ByteBuf _buf)
    {
        return new i18n.I18L(_buf);
    }

    /// <summary>
    /// 本地化key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 原始值
    /// </summary>
    public readonly string OriginText;
    /// <summary>
    /// 繁体
    /// </summary>
    public readonly string TextTw;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string TextEn;
   
    public const int __ID__ = 48713708;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "originText:" + OriginText + ","
        + "textTw:" + TextTw + ","
        + "textEn:" + TextEn + ","
        + "}";
    }
}

}

